track_parcel:
  fields:
    tracking_code:
      required: true
      example: "UUS-SYNTHETIC-123456"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "UUS-SYNTHETIC-123456"
      selector:
        text:
